version: '3'

services:
  rusher:
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres 
      PGDATABASE: dev_rushing
      PGPORT: 5432
      PGHOST: db 
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  volumes:
    pgdata:
